---
- name: install gogs dependencies
  package: "name={{item}} state=present update_cache=yes"
  with_items:
    - git
    - unzip

- name: create git user
  user: name=git comment="Git User"

- name: get gogs binary
  unarchive: src={{gogs_url}} dest=/home/git copy=no owner=git group=git creates=/home/git/gogs

- name: create init file
  command: "cp /home/git/gogs/scripts/init/debian/gogs /etc/init.d/" 
  args:
    creates: "/etc/init.d/gogs"

- name: make init file executable
  file: path=/etc/init.d/gogs mode=0755

- name: create gogs conf dir
  file:  path=/home/git/gogs/custom/conf state=directory owner=git group=git

- name: create gogs conf
  template: src=app.ini.j2 dest=/home/git/gogs/custom/conf/app.ini owner=git group=git
  notify: restart gogs

- name: start gogs
  service: name=gogs state=started
