---
- hosts: group_smooth
  become: yes
  vars:
    - ansible_user: ubuntu
    - nginx_sites:
        default:
            - listen 80
            - server_name _
            - location / {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $remote_addr;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Host $http_host;
                proxy_set_header Origin "";
                proxy_redirect off;
                proxy_http_version 1.1;
                proxy_buffering off;
                chunked_transfer_encoding off;
                proxy_pass http://127.0.0.1:8000/;
              }

  roles:
    - drone
    - jdauphant.nginx

- hosts: group_groove
  become: yes
  vars:
    - ansible_user: ubuntu
    - nginx_sites:
        default:
            - listen 80
            - server_name _
            - location / {
                proxy_pass http://localhost:3000;
              }

  roles:
    - gogs
    - jdauphant.nginx
